// SPDX-License-Identifier: GPL-3.0-only
package helium314.keyboard.latin.dictionary

import java.security.MessageDigest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class VietnamesePhraseModelTest {
    @Test
    fun predictsMandatedVietnameseBigramsWithNfcAndCaseInsensitiveLookup() {
        val model = VietnamesePhraseModelData.parse(modelText, manifestFor(modelText, entryCount = 6))

        assertEquals("sinh", model.predict(arrayOf("ho\u0323c")).first().word)
        assertEquals("nghệ", model.predict(arrayOf("CÔNG")).first().word)
        assertEquals("Nam", model.predict(arrayOf("Việt")).first().word)
    }

    @Test
    fun prefersTrigramBeforeLastWordBigramAndKeepsFallbacksBounded() {
        val model = VietnamesePhraseModelData.parse(modelText, manifestFor(modelText, entryCount = 6))

        assertEquals(listOf("giỏi", "viên"), model.predict(arrayOf("HỌC", "SINH")).map { it.word })
        assertEquals(listOf("giỏi"), model.predict(arrayOf("học", "sinh"), limit = 1).map { it.word })
    }

    @Test
    fun ignoresInvalidContextTokensWithoutThrowingOrFallingBackToOlderWords() {
        val model = VietnamesePhraseModelData.parse(modelText, manifestFor(modelText, entryCount = 6))

        assertTrue(model.predict(arrayOf("42")).isEmpty())
        assertTrue(model.predict(arrayOf("học", "42")).isEmpty())
        assertTrue(model.predict(arrayOf("<S>", "học")).isEmpty())
    }

    @Test
    fun rejectsUnboundedOrMalformedRows() {
        val duplicate = modelText.replace("2\t980\tViệt\tNam", "2\t980\tviệt\tNam\n2\t970\tViệt\tNam")
        assertFailsWith<IllegalArgumentException> {
            VietnamesePhraseModelData.parse(duplicate, manifestFor(duplicate, entryCount = 7))
        }
        val invalidToken = modelText.replace("2\t1000\thọc\tsinh", "2\t1000\thọc\tsinh viên")
        assertFailsWith<IllegalArgumentException> {
            VietnamesePhraseModelData.parse(invalidToken, manifestFor(invalidToken, entryCount = 6))
        }
    }

    @Test
    fun checksumVerifierRejectsTampering() {
        val bytes = modelText.encodeToByteArray()
        assertTrue(VietnamesePhraseModelVerifier.matches(manifestFor(modelText, entryCount = 6), bytes))
        assertFalse(VietnamesePhraseModelVerifier.matches(manifestFor(modelText, entryCount = 6), bytes + 0))
    }

    @Test
    fun manifestParserRejectsWrongArtifactAndUnexpectedFields() {
        val valid = manifestJson()
        assertEquals("dicts/vi_phrase_model_v1.tsv", VietnamesePhraseModelManifest.parse(valid).artifact)
        assertFailsWith<IllegalArgumentException> {
            VietnamesePhraseModelManifest.parse(valid.replace("vi_phrase_model_v1.tsv", "other.tsv"))
        }
        assertFailsWith<IllegalArgumentException> {
            VietnamesePhraseModelManifest.parse(valid.replace(
                "\"version\": \"fixture\"",
                "\"version\": \"fixture\", \"unexpected\": true",
            ))
        }
    }

    private fun manifestFor(model: String, entryCount: Int): VietnamesePhraseModelManifest =
        VietnamesePhraseModelManifest(
            artifact = "dicts/vi_phrase_model_v1.tsv",
            locale = "vi",
            version = "fixture",
            source = "test seed",
            license = "GPL-3.0-only",
            sha256 = MessageDigest.getInstance("SHA-256").digest(model.encodeToByteArray())
                .joinToString("") { "%02x".format(it.toInt() and 0xff) },
            byteCount = model.encodeToByteArray().size.toLong(),
            formatVersion = 1,
            entryCount = entryCount,
            maxEntries = 128,
            maxCandidatesPerContext = 3,
            sourceSha256 = "0".repeat(64),
            sourceByteCount = 1,
            sourceLicense = "GPL-3.0-only",
        )

    private fun manifestJson(): String = """
        {
          "artifact": "dicts/vi_phrase_model_v1.tsv",
          "byteCount": 1,
          "entryCount": 1,
          "formatVersion": 1,
          "license": "GPL-3.0-only",
          "locale": "vi",
          "maxCandidatesPerContext": 1,
          "maxEntries": 1,
          "sha256": "0000000000000000000000000000000000000000000000000000000000000000",
          "source": "test",
          "sourceByteCount": 1,
          "sourceLicense": "GPL-3.0-only",
          "sourceSha256": "0000000000000000000000000000000000000000000000000000000000000000",
          "version": "fixture"
        }
    """.trimIndent()

    private companion object {
        val modelText = listOf(
            "# SPDX-License-Identifier: GPL-3.0-only",
            "# Generated by tools/vietnamese/build_phrase_model.py; do not edit manually.",
            "# format: order<TAB>score<TAB>context word(s)<TAB>candidate",
            "2\t1000\thọc\tsinh",
            "2\t995\tcông\tnghệ",
            "2\t990\tViệt\tNam",
            "2\t960\tsinh\tviên",
            "3\t1000\thọc\tsinh\tgiỏi",
            "3\t995\tcông\tnghệ\tthông",
        ).joinToString("\n", postfix = "\n")
    }
}
